# Generated by Django 2.2 on 2019-04-27 03:04

from django.db import migrations


def forwards_func(apps, schema_editor):
    """
    :param apps:
    :param schema_editor:
    :return:
    """
    permission_group = apps.get_model("rbac", "PermissionGroup")
    menu = apps.get_model("rbac", "Menu")
    menu_user = menu.objects.get(id=1, name="用户与角色")
    menu_list = menu.objects.get(id=2, name="菜单管理")
    menu_pers = menu.objects.get(id=3, name="权限和权限组")
    menu_current = menu.objects.get(id=4, name="当前用户")

    db_alias = schema_editor.connection.alias
    permission_group.objects.using(db_alias).bulk_create([
        permission_group(id=1, menu=menu_user, name="用户管理"),
        permission_group(id=2, menu=menu_list, name="菜单管理"),
        permission_group(id=3, menu=menu_pers, name="权限和权限组"),
        permission_group(id=4, menu=menu_current, name="当前用户")
    ])


def reverse_func(apps, schema_editor):
    """
    :param apps:
    :param schema_editor:
    :return:
    """
    permission_group = apps.get_model("rbac", "PermissionGroup")
    db_alias = schema_editor.connection.alias
    permission_group.objects.using(db_alias).filter(menu=1).filter(name="用户管理").delete()
    permission_group.objects.using(db_alias).filter(menu=2).filter(name="菜单管理").delete()
    permission_group.objects.using(db_alias).filter(menu=3).filter(name="权限和权限组").delete()
    permission_group.objects.using(db_alias).filter(menu=4).filter(name="当前用户").delete()


class Migration(migrations.Migration):
    dependencies = [
        ('rbac', '0001_initial'),
        ('rbac', '0002_auto_20190520_0000'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func)
    ]
