# Generated by Django 2.2 on 2019-04-27 03:04

from django.db import migrations


def forwards_func(apps, schema_editor):
    """
    :param apps:
    :param schema_editor:
    :return:
    """
    permission = apps.get_model("rbac", "Permission")
    permission_group = apps.get_model("rbac", "PermissionGroup")

    var_g1 = permission_group.objects.get(id=1)
    var_g2 = permission_group.objects.get(id=2)
    var_g3 = permission_group.objects.get(id=3)
    var_g4 = permission_group.objects.get(id=4)

    db_alias = schema_editor.connection.alias
    permission.objects.using(db_alias).bulk_create([
        # 用户初始化
        permission(id=1, title="添加用户", code="insert", group=var_g1, url='/rbac/user/add.html', group_menu=None),
        permission(id=2, title="删除用户", code="delete", group=var_g1, url="/rbac/user/del/(\\d+).html", group_menu=None),
        permission(id=3, title="修改用户", code="update", group=var_g1, url="/rbac/user/edit/(\\d+).html", group_menu=None),
        permission(id=4, title="用户列表", code="select", group=var_g1, url='/rbac/user/list.html', group_menu=None),
        # 菜单权限初始化
        permission(id=5, title="添加菜单", code="insert", group=var_g2, url='/rbac/menu/add.html', group_menu=None),
        permission(id=6, title="删除菜单", code="delete", group=var_g2, url="/rbac/menu/del/(\\d+).html", group_menu=None),
        permission(id=7, title="修改菜单", code="update", group=var_g2, url="/rbac/menu/edit/(\\d+).html", group_menu=None),
        permission(id=8, title="菜单列表", code="select", group=var_g2, url='/rbac/menu/list.html', group_menu=None),
        # 权限组权限初始化
        permission(id=9, title="添加权限组", code="insert", group=var_g3, url='/rbac/permission_group/add.html', group_menu=None),
        permission(id=10, title="删除权限组", code="delete", group=var_g3, url='/rbac/permission_group/del/(\\d+).html',
                   group_menu=None),
        permission(id=11, title="修改权限组", code="update", group=var_g3, url='/rbac/permission_group/edit/(\\d+).html',
                   group_menu=None),
        permission(id=12, title="权限组列表", code="select", group=var_g3, url='/rbac/permission_group/list.html',
                   group_menu=None),
        # 权限内容初始化
        permission(id=13, title="添加权限", code="insert", group=var_g3, url='/rbac/permission/add.html', group_menu=None),
        permission(id=14, title="删除权限", code="delete", group=var_g3, url='/rbac/permission/del/(\\d+).html', group_menu=None),
        permission(id=15, title="修改权限", code="update", group=var_g3, url='/rbac/permission/edit/(\\d+).html', group_menu=None),
        permission(id=16, title="权限列表", code="select", group=var_g3, url='/rbac/permission/list.html', group_menu=None),
        # 角色权限初始化
        permission(id=17, title="添加角色", code="insert", group=var_g1, url='/rbac/role/add.html', group_menu=None),
        permission(id=18, title="删除角色", code="delete", group=var_g1, url='/rbac/role/del/(\\d+).html', group_menu=None),
        permission(id=19, title="修改角色", code="update", group=var_g1, url='/rbac/role/edit/(\\d+).html', group_menu=None),
        permission(id=20, title="角色列表", code="select", group=var_g1, url='/rbac/role/list.html', group_menu=None),
        # 当前用户修改
        permission(id=21, title="修改密码", code="update", group=var_g4, url='/rbac/user/password.html', group_menu=None),
    ])


def reverse_func(apps, schema_editor):
    permission = apps.get_model("rbac", "Permission")
    db_alias = schema_editor.connection.alias
    permission.objects.using(db_alias).filter(id=1).delete()
    permission.objects.using(db_alias).filter(id=2).delete()
    permission.objects.using(db_alias).filter(id=3).delete()
    permission.objects.using(db_alias).filter(id=4).delete()
    permission.objects.using(db_alias).filter(id=5).delete()
    permission.objects.using(db_alias).filter(id=6).delete()
    permission.objects.using(db_alias).filter(id=7).delete()
    permission.objects.using(db_alias).filter(id=8).delete()
    permission.objects.using(db_alias).filter(id=9).delete()
    permission.objects.using(db_alias).filter(id=10).delete()
    permission.objects.using(db_alias).filter(id=11).delete()
    permission.objects.using(db_alias).filter(id=12).delete()
    permission.objects.using(db_alias).filter(id=13).delete()
    permission.objects.using(db_alias).filter(id=14).delete()
    permission.objects.using(db_alias).filter(id=15).delete()
    permission.objects.using(db_alias).filter(id=16).delete()
    permission.objects.using(db_alias).filter(id=17).delete()
    permission.objects.using(db_alias).filter(id=18).delete()
    permission.objects.using(db_alias).filter(id=19).delete()
    permission.objects.using(db_alias).filter(id=20).delete()
    permission.objects.using(db_alias).filter(id=21).delete()
    permission.objects.using(db_alias).filter(id=22).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('rbac', '0001_initial'),
        ('rbac', '0002_auto_20190520_0000'),
        ('rbac', '0003_auto_20190520_0001'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func)
    ]
