# Generated by Django 2.2 on 2019-04-27 03:04

from django.db import migrations
from django.contrib.auth.hashers import make_password


def forwards_func(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Department = apps.get_model("rbac", "Department")
    UserInfo = apps.get_model("rbac", "UserInfo")
    create_user = Department.objects.get(title="运维部")

    UserInfo.object.using(db_alias).create(
        id=1,
        username="admin@yuv.cc",
        password=make_password(password="dkmgame123", hasher="pbkdf2_sha256"),
        first_name="管",
        last_name="理员",
        mobile="18602841836",
        department=create_user,
        is_active=1,
        is_staff=1,
        is_superuser=1
    )


def reverse_func(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    UserInfo = apps.get_model("rbac", "UserInfo")
    UserInfo.objects.using(db_alias).filter(id=1).filter(username='admin@yuv.cc').delete()


class Migration(migrations.Migration):
    dependencies = [
        ('rbac', '0001_initial'),
        ('rbac', '0002_auto_20190520_0000'),
        ('rbac', '0003_auto_20190520_0001'),
        ('rbac', '0004_auto_20190520_0001'),
        ('rbac', '0005_auto_20190521_0001'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func)
    ]
